### ISSUE TITLE
NaN ARI with perfect match

### ISSUE THREAD

**Issue by mattiacampana** [cmccomb/rand_index#1]
I think there is a bug somewhere because, for a perfect match, the ARI computation gives `NaN`.

Example:
`
a=[1,1,1]
b=[1,1,1]

rand_index(a, b, 'adjusted')`

This should give `1`, but the result is `NaN`. The same for `b=[0,0,0]` or similar configurations.

**Comment by cmccomb** [comment]
Turns out there was a divide by zero error. This has been fixed, and I've added a new test case that aligns to the NaN output you found. Thanks for catching it!
